#page title
page_title                                : Bullets                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                            # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Bullets                                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free & Pro version (coming soon...)                                         # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Con bullets controla el día a día de tus subscripciones.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Josa Vicente                                
your_link                                 : https://github.com/josavicente/                     
your_city                                 : Barcelona                               
email_address                             : jvicenpe@gmail.com
facebook_username                         :                                           
instagram_username                        : josavicente
twitter_username                          : josavicente
github_username                           : josavicente
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Diseño minimalista
    description                           : Apariencia limpia y sencilla. Personalización de los colores
    fontawesome_icon_name                 : grip-lines
    
  - title                                 : Darkmode
    description                           : Modo oscuro sincronizado con el sistema
    fontawesome_icon_name                 : mobile

  - title                                 : Alerts
    description                           : Notificaciones de pago con antelación y hora personalizadas
    fontawesome_icon_name                 : user-clock

  - title                                 : Currency conversion
    description                           : Conversión a la moneda personalizada del usuario
    fontawesome_icon_name                 : exchange-alt

  - title                                 : 32 monedas soportadas
    description                           : Elige entre 32 monedas. El valor de cambio se extrae de exchangeratesapi.io
    fontawesome_icon_name                 : coins
  
  - title                                 : Listado de subscripciones pre instaladas
    description                           : Elige entre 77 servicios categorizados. Se irán añadiendo más.
    fontawesome_icon_name                 : th-list

  - title                                 : Creación ilimitada de subscripciones personalizadas
    description                           : Crea tantas subscripciones como necesites. Personaliza el color, elije su tipo, forma de pago y ciclo.
    fontawesome_icon_name                 : magic

  - title                                 : Categorización de subscripciones
    description                           : Elige entre varias categorias para organizar tus subscripciones.
    fontawesome_icon_name                 : tape

  - title                                 : Resúmen mensual
    description                           : Información del pago realizado hasta el momento y el total del mes en curso.
    fontawesome_icon_name                 : chart-line

  - title                                 : Widget
    description                           : Siempre al día de la siguiente subscripción que será cobrada.
    fontawesome_icon_name                 : mobile-alt



# Theme Settings
topbar_color                              : "#FFFFFF"
topbar_transparency                       : 1
topbar_title_color                        : "#000000"

cover_image                               :                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#FFFFFF"
cover_overlay_transparency                : 1

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#FFFFFF"

link_color                                : "#1d63ea"

app_title_color                           : "#000000"
app_price_color                           : "#000000"
app_description_color                     : "#000000"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
